### ISSUE TITLE
[BUG]: After finishing a race I got the following

### ISSUE THREAD

**Issue by trace2798** [webdevcody/code-racer#422] opened 2023-07-19 11:44 UTC
### Description

After finishing a race I got this
![image](https://github.com/webdevcody/code-racer/assets/113078518/f398459f-b165-4124-8745-612becc77dfb)

### (optional) What browsers are you seeing the problem on?

Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by plbstl** [comment] 2023-07-19 19:16
@trace2798 can you show what is logged in your browser's console?

**Comment by jordanthewebdesigner** [comment] 2023-07-20 03:01
I think I was able to get this same error. I think it might only happen the 1st time you race with a new profile, but I haven't confirmed yet.

Warning: Only plain objects can be passed to Client Components from Server Components. Decimal objects are not supported.
  {id: ..., userId: ..., createdAt: Date, accuracy: Decimal, cpm: ..., takenTime: ..., errorCount: ..., snippetId: ...}
                                                    ^^^^^^^
Warning: Only plain objects can be passed to Client Components from Server Components. Decimal objects are not supported.
  {id: ..., userId: ..., createdAt: ..., accuracy: Decimal, cpm: ..., takenTime: ..., errorCount: ..., snippetId: ...}

**Comment by sudo-adduser-jordan** [comment] 2023-07-20 04:03
Did this issue happen locally or in production?

**Comment by jordanthewebdesigner** [comment] 2023-07-20 04:13
I saw an error screen that I think was the same as the screenshot in production, but it went away when I refreshed the page.

When I ran it locally I was able to get the error from the console that I pasted. But I had to stop investigating before I could get it to happen again.

**Comment by elwin212** [comment] 2023-07-20 06:51
I have this error in production as well, but I can't reproduce this error. I'm using Chrome.
I think jordan is correct, this might happen when a new user play first time.

**Comment by scape76** [comment] 2023-07-20 08:19
related to #432, since it was fixed, closing this

**Comment by sudo-adduser-jordan** [comment] 2023-07-21 09:46
Production. First race completion. Had to reload. Results were recorded.

![Screenshot 2023-07-21 022957](https://github.com/webdevcody/code-racer/assets/108599131/ce6b8987-7466-4bcb-b10f-a88f854feeca)

**Comment by sudo-adduser-jordan** [comment] 2023-07-21 09:48
May need to be reopened.

**Closed** 2023-07-21 17:15 UTC
Labels: bug
