### ISSUE TITLE
[BUG]: Issue with language select typeahead on race selection page.

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#448] opened 2023-07-20 17:19 UTC
### Description

<img width="496" alt="Screenshot 2023-07-20 at 1 18 19 PM" src="https://github.com/webdevcody/code-racer/assets/123222405/934218d0-4b66-45f8-bb87-e8b2bb6a26b0">

- Go to the language select dropdown.  
- type "tx"
- notice you get no results
- backspace the "x"
- type "y"
- I would expect "Typescript" to show up as an option, but it's still blank

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by txmho** [comment] 2023-07-20 21:05
Hey, I would like to work on this issue :)

**Comment by yash91989201** [comment] 2023-07-21 03:23
Perhaps, adding a custom filter option by setting "shouldFilter" to false within the Command component could solve the problem.

Can you assign this issue to me so that I can work on the solution?

**Comment by yash91989201** [comment] 2023-07-21 04:48
I guess there is an issue with the filter option used because when I pass a custom filter option it doesnot work , so I set the shouldFilter prop to false and implemented a search function that takes in values and string based on which the menu item is rendered . 

Is this a viable approach to take ?

**Comment by DeveloperParth** [comment] 2023-07-23 07:47
I tried reproducing this issue but it works as intended without any bugs Ive tried it on Firefox, Chrome and edge too and it seems to work finr

**Comment by scape76** [comment] 2023-07-23 09:09
Interesting, I think someone fixed this already

**Closed by scape76** 2023-07-23 09:09 UTC
Labels: bug, good first issue

**Comment by DeveloperParth** [comment] 2023-07-23 09:22
#452 seems like it was fixed in this pr but they didn't mention issue correctly i guess
